# Generated by Django 5.2.1 on 2025-05-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('F', 'Finalizada'), ('A', 'Em andamento'), ('B', 'Em breve')], default='I', max_length=1),
        ),
    ]
