# Generated by Django 5.2.1 on 2025-05-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_meeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('F', 'Finalizada'), ('A', 'Em andamento'), ('I', 'Inicia em breve')], default='I', max_length=1),
        ),
    ]
