# Generated by Django 5.2.1 on 2025-05-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_meeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('PRO', 'Professor')], default='ADM', max_length=3),
        ),
    ]
